added test resource manager
mars-planet/mars_city pull request #20
Opened 2017-05-23 13:58 UTC by aneesh-joshi

to be reviewed for correcting implementation (if required)

2017-05-24 14:50 UTC, mtambos requested changes
Please correct the coding style using flake8.
You should also use a ORM instead of writing the queries by hand. I like peewee.

Finally, there should be no code outside functions, unless it is absolutely necessary.

In the case of the tests, they should go into a unittest.TestCase class

2017-05-31 17:48 UTC, mtambos commented on MOCC/src/configurations/test_aneesh/db_setup.py
> +import MySQLdb
make code flake8 compliant

2017-05-31 17:48 UTC, mtambos commented on MOCC/src/configurations/test_aneesh/db_setup.py
> +import MySQLdb
use peewee instead of writing queries by hand

2017-05-31 17:49 UTC, mtambos commented on MOCC/src/configurations/test_aneesh/db_setup.py
> +import MySQLdb
put everything inside functions and then use if __name__ == '__main__'

2017-05-31 17:49 UTC, mtambos commented on MOCC/src/configurations/test_aneesh/resource_manager_ds_setup.py
> +import PyTango
make code flake8 compliant
put everything inside functions and then use if name == 'main'

2017-05-31 17:49 UTC, mtambos commented on MOCC/src/configurations/test_aneesh/resource_manager_tester.py
> +import PyTango
make code flake8 compliant
put everything inside functions and then use if name == 'main'

2017-05-31 17:50 UTC, mtambos commented on MOCC/src/configurations/test_aneesh/ResourceManagerDS.py
> +"""resource manager tango device server"""
make code flake8 compliant

2017-05-31 17:50 UTC, mtambos commented on MOCC/src/configurations/Resource-Manager/resource_manager_ds_setup.py
> +import PyTango
make code flake8 compliant
put everything inside functions and then use if name == 'main'

2017-05-31 17:50 UTC, mtambos commented on MOCC/src/configurations/Resource-Manager/TestResourceManager.py
> +import unittest
make code flake8 compliant

2017-05-31 17:50 UTC, mtambos commented on MOCC/src/configurations/Resource-Manager/ResourceManagerDS.py
> +"""
make code flake8 compliant

2017-06-01 00:52 UTC, aneesh-joshi commented on MOCC/src/configurations/test_aneesh/db_setup.py
> +import MySQLdb
Sorry
This was an older version in which I was using MySQL.
An error while pushing caused it to still exist.
Have removed it now.

2017-06-01 06:39 UTC, merged

2017-06-01 09:30 UTC, aneesh-joshi commented
Is this way of passing data between device servers (through strings) an acceptable method?

Is there any way to pass python objects?

2017-06-02 08:35 UTC, mtambos commented
No there's no way of passing arbitrary objects between tango device servers.
That's something we're discussing with tango's team at the moment, but it's not in their near future plans.