Defining a subset of methods as in PyTango's DeviceProxy
mars-planet/mars_city pull request #49
Opened 2017-11-05 16:51 UTC by arpitgogia

2017-11-15 09:28 UTC, mtambos requested changes

2017-11-15 09:28 UTC, mtambos commented on MOCC/src/configurations/Comm-Layer/device_proxy.py
> +from config_manager import ConfigManager
The config manager is not a library (yet). It is a REST server, so you need to make a REST call to get the dev_name <-> IP:port mapping

2017-11-15 09:28 UTC, mtambos commented on MOCC/src/configurations/Comm-Layer/device_proxy.py
> +        raise NotImplementedError
you forgot the parentheses after "...Error"

2017-12-06 06:42 UTC, arpitgogia commented on MOCC/src/configurations/Comm-Layer/device_proxy.py
> +from config_manager import ConfigManager
Where do I get the address for the REST server, or is it fixed?

2017-12-11 10:20 UTC, mtambos commented on MOCC/src/configurations/Comm-Layer/device_proxy.py
> +        raise (NotImplementedError)
this should be raise NotImplementedError()

2017-12-11 10:29 UTC, mtambos approved these changes

2017-12-15 08:22 UTC, merged